### ISSUE TITLE
Vnc-viewer crashes when using scbw with --human option

### ISSUE THREAD

**Issue by grzegorzborkowski** [Games-and-Simulations/sc-docker#10]
Hi,

I am using Ubuntu 16.04. I haven't found any problems when running two bots against each other. When executing 
```
scbw --bots "PurpleWave" --human
```
Here's what I get:
```
INFO checking docker version
INFO checking docker can run
INFO checking docker has network sc_net
INFO checking if there is local image starcraft:game
INFO found bot in /home/grzegorz/.scbw/bots/PurpleWave
INFO Logs can be found in /home/grzegorz/.scbw/logs/GAME_GAME_B1E6A49A_*
INFO launched HumanPlayer:human:R in container GAME_B1E6A49A_0_human
INFO launched BotPlayer:PurpleWave:P in container GAME_B1E6A49A_1_PurpleWave
INFO Checking if game has launched properly...
INFO Launching vnc viewer for HumanPlayer:human:R on port 5900
INFO 
In headful mode, you must specify and start the game manually.
Select the map, wait for bots to join the game and then start the game.
INFO Waiting until game is finished.
```

Then I am trying to launch vnc-viewer on port 5900 but I got error: "The connection was refused by the computer". I can enter the game using vnc-viewer and port 5901 as PurpleWave.
I am using RealVNC. I tried with scbw v 0.2a8

**Comment by certicky** [comment]
Same here.

**Comment by michalsustr** [comment]
There was a bug with determining when is the game over. Please try new version:
```
pip3.6 install scbw==0.2a17
docker rm $(docker ps -a -q)
docker rmi starcraft:game
docker pull ggaic/starcraft:java
```

**Comment by michalsustr** [comment]
I also updated the docs about bot playing on two computers (two IP addresses): https://github.com/Games-and-Simulations/sc-docker/blob/master/USAGE.md#play-on-the-host

**Comment by grzegorzborkowski** [comment]
It works :) Thanks

**Comment by michalsustr** [comment]
Ok I assume it also works for Michal, closing.
