### ISSUE TITLE
No maps under BroodWar folder

### ISSUE THREAD

**Issue by Weeep** [Games-and-Simulations/sc-docker#19]
### expected behaviour
sscai map folder is under _/app/sc/maps/BroodWar_.

### actual behaviour
sscai map folder is under _/app/sc/maps_.

I don't know it's a bug or I did something wrong but the game is looking for the maps under BroodWar directory, but it is empty since _~/.scbw/maps_ directory mapped to _/app/sc/maps_ and I cannot navigate up in the game (or can I?)
![nomap](https://user-images.githubusercontent.com/3452223/35349744-17ab4a80-013c-11e8-8914-9b74f0076c57.png)

I can workaround this to create a softlink on the host machine:

> ~/.scbw/maps$ ls
> replays  sscai
> ~/.scbw/maps$ ln -s . BroodWar
> ~/.scbw/maps$ ls
> BroodWar  replays  sscai

After this it works well.

### steps to reproduce

```
~/.scbw/maps$ scbw.play --bots krasi0 CherryPi --headless --log_level=DEBUG
INFO checking docker version
DEBUG Using docker API version b"'1.32'\n"
INFO checking docker can run
INFO checking docker has network sc_net
DEBUG docker network id: b'86190ab5307a\n'
INFO checking if there is local image starcraft:game
DEBUG docker image id: b'22dce6244e5c\n'
DEBUG checking bot in /home/dann/.scbw/bots/krasi0
DEBUG found bot in /home/dann/.scbw/bots/krasi0
DEBUG checking bot in /home/dann/.scbw/bots/CherryPi
DEBUG found bot in /home/dann/.scbw/bots/CherryPi
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_EA260F9D_0_krasi0', '--volume', '/home/dann/.scbw/logs:/app/logs:rw', '--volume', '/home/dann/.scbw/bots:/app/bots:ro', '--volume', '/home/dann/.scbw/maps:/app/sc/maps:rw', '--volume', '/home/dann/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '/home/dann/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '--volume', '/home/dann/.scbw/bots/krasi0/write/GAME_EA260F9D_0:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=krasi0', '-e', 'PLAYER_RACE=T', '-e', 'NTH_PLAYER=0', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_EA260F9D', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=krasi0', '-e', 'BOT_FILE=krasi0AIClient.exe', 'starcraft:game', '/app/play_bot.sh', '--game', 'GAME_EA260F9D', '--name', 'krasi0', '--race', 'T', '--lan', '--host', '--map', '/app/sc/maps/sscai/(2)Benzene.scx']
INFO launched BotPlayer:krasi0:T in container GAME_EA260F9D_0_krasi0
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_EA260F9D_1_CherryPi', '--volume', '/home/dann/.scbw/logs:/app/logs:rw', '--volume', '/home/dann/.scbw/bots:/app/bots:ro', '--volume', '/home/dann/.scbw/maps:/app/sc/maps:rw', '--volume', '/home/dann/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '/home/dann/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '--volume', '/home/dann/.scbw/bots/CherryPi/write/GAME_EA260F9D_1:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=CherryPi', '-e', 'PLAYER_RACE=Z', '-e', 'NTH_PLAYER=1', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_EA260F9D', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=CherryPi', '-e', 'BOT_FILE=BWEnv.dll', 'starcraft:game', '/app/play_bot.sh', '--game', 'GAME_EA260F9D', '--name', 'CherryPi', '--race', 'Z', '--lan', '--join']
INFO launched BotPlayer:CherryPi:Z in container GAME_EA260F9D_1_CherryPi
INFO Checking if game has launched properly...
DEBUG running containers: ['22376cd831e3', '678e1bc5d3e1']
INFO Waiting until game is finished...
DEBUG running containers: ['22376cd831e3', '678e1bc5d3e1']
DEBUG running containers: ['22376cd831e3', '678e1bc5d3e1']
DEBUG running containers: ['22376cd831e3', '678e1bc5d3e1']
^CWARNING Caught interrupt, shutting down containers
WARNING This can take a moment, please wait.
DEBUG running containers: ['22376cd831e3', '678e1bc5d3e1']
22376cd831e3
678e1bc5d3e1
INFO Game cancelled.
~/.scbw/maps$ 
```

### operating system

    linux (ubuntu 16.04)

Ubuntu `lsb_release -a`:

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.2 LTS
    Release:	16.04
    Codename:	xenial

### docker version

output of command `docker version`:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### scbw version

output of command `scbw.play -v`

    0.2a20

**Comment by michalsustr** [comment]
Hmm, I think the game creates the empty BroodWar directory. Maybe you didn't have write permissions for the maps folder?

I'll create empty BroodWar folder by default.

**Comment by Weeep** [comment]
Hi, 

Thanks, yes, had no permission to write maps folder.
The owner and group of maps are very strange in the docker:

> rwxr-xr-x 1 starcraft users     4096 Jan 23 21:05 characters
> drwxrwxr-x 1 starcraft users     4096 Jan 23 21:05 bwapi-data
> drwxrwxrwx 5     **44222 64000**     4096 Jan 28 15:30 maps

I don't know why, but I gave write permission to everyone, now it works.

(But still, I have to navigate up from BroodWar folder because the maps are there but OK, that is not a big deal.)

**Comment by michalsustr** [comment]
I'll try to see if there is something I can do to make sure the uid/gids map correctly, but it seems like this is an entangled issue in docker itself. There are multiple ways docker can run (cgroups in linux, and on VM in Mac/Win) and they have different permission/user handling.

> I have to navigate up from BroodWar folder because the maps are there but OK, that is not a big deal.
Yes, that is normal behaviour.

Closing.
