### ISSUE TITLE
Unable create output file

### ISSUE THREAD

**Issue by Payne-X6** [Games-and-Simulations/sc-docker#21]
### actual behaviour
After end of game, there is no file in output (write) directory. Only folder for actual game is created.

### expected behaviour
There should be any file that is created by the bot (Java code).

### steps to reproduce
- Create empty JAVA bot 
- in "onStart()" method add creating of new file on path "someFile.txt"
- write something into created file
- move bot into .scbw/bots folder
- start game
- after few moments end game (F10 -> Exit game -> Surrender)
- look into folder "pathToMyBot/write/GAME_gameId_0/" - in my case is folder empty

### idea

When I print absolute path to "someFile.txt", I get "Z:\\app\sc\someFile.txt". Should I save files into other directory?? 

### log

scbw.play --bots PayneJr "Iron bot" --show_all --log_level=DEBUG
INFO checking docker version
DEBUG Using docker API version b"'1.35'\n"
INFO checking docker can run
INFO checking docker has network sc_net
DEBUG docker network id: b'88e05cc0c7dd\n'
INFO checking if there is local image starcraft:game
DEBUG docker image id: b'7f8ed28b66dc\n'
DEBUG checking bot in /home/payne/.scbw/bots/PayneJr
DEBUG found bot in /home/payne/.scbw/bots/PayneJr
DEBUG checking bot in /home/payne/.scbw/bots/Iron bot
DEBUG found bot in /home/payne/.scbw/bots/Iron bot
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_4C403B72_0_PayneJr', '--volume', '/home/payne/.scbw/logs:/app/logs:rw', '--volume', '/home/payne/.scbw/bots:/app/bots:ro', '--volume', '/home/payne/.scbw/maps:/app/sc/maps:rw', '--volume', '/home/payne/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '/home/payne/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '-p', '5900:5900', '--volume', '/home/payne/.scbw/bots/PayneJr/write/GAME_4C403B72_0:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=PayneJr', '-e', 'PLAYER_RACE=P', '-e', 'NTH_PLAYER=0', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_4C403B72', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=PayneJr', '-e', 'BOT_FILE=bot.jar', 'starcraft:game', '/app/play_bot.sh', '--headful']
INFO launched BotPlayer:PayneJr:P in container GAME_4C403B72_0_PayneJr
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_4C403B72_1_Iron_bot', '--volume', '/home/payne/.scbw/logs:/app/logs:rw', '--volume', '/home/payne/.scbw/bots:/app/bots:ro', '--volume', '/home/payne/.scbw/maps:/app/sc/maps:rw', '--volume', '/home/payne/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '/home/payne/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '-p', '5901:5900', '--volume', '/home/payne/.scbw/bots/Iron bot/write/GAME_4C403B72_1:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=Iron bot', '-e', 'PLAYER_RACE=T', '-e', 'NTH_PLAYER=1', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_4C403B72', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=Iron bot', '-e', 'BOT_FILE=Iron.dll', 'starcraft:game', '/app/play_bot.sh', '--headful']
INFO launched BotPlayer:Iron bot:T in container GAME_4C403B72_1_Iron bot
INFO Checking if game has launched properly...
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
INFO Launching vnc viewer for BotPlayer:PayneJr:P on port 5900
INFO Launching vnc viewer for BotPlayer:Iron bot:T on port 5901
INFO 
In headful mode, you must specify and start the game manually.
Select the map, wait for bots to join the game and then start the game.
INFO Waiting until game is finished...
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4', '854eec5169e5']
DEBUG running containers: ['c13ecb48c8f4']
DEBUG running containers: []
0
INFO Game GAME_4C403B72 finished in 55.429983615875244 seconds.
INFO Logs are saved here:
INFO /home/payne/.scbw/logs/GAME_4C403B72_0_PayneJr_bot.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_0_PayneJr_game.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_0_PayneJr_xvfb.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_0_PayneJr_xvnc.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_1_Iron bot_bot.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_1_Iron bot_game.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_1_Iron bot_xvfb.log
INFO /home/payne/.scbw/logs/GAME_4C403B72_1_Iron bot_xvnc.log
INFO Replays are saved here:
INFO /home/payne/.scbw/maps/replays/2018-01-29_GAME_4C403B72_0.rep
INFO /home/payne/.scbw/maps/replays/2018-01-29_GAME_4C403B72_1.rep
INFO Winner is BotPlayer:PayneJr:P (player 0)

### operating system
    linux 4.4.0-112-generic

    Distributor ID:    Ubuntu
    Description:    Ubuntu 16.04.3 LTS
    Release:    16.04
    Codename:    xenial

### docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

### scbw version

0.2a20

**Comment by michalsustr** [comment]
> Should I save files into other directory??
Yes :) Bots should write to `bwapi-data/write` as in the SSCAIT / AIIDE rules: 
http://sscaitournament.com/index.php?action=rules

Please also make sure that you have write permissions on the host folder.

TODO: This should be included in the docs, or at least a link to it.
TODO: Automatically check host permissions.
