### ISSUE TITLE
No game results saved

### ISSUE THREAD

**Issue by kant2002** [Games-and-Simulations/sc-docker#31]
### Expected behaviour

The game should finish without any errors in the console, if actual game is finished fine.

### Actual behaviour
    INFO Game GAME_C5022697 finished in 326.08 seconds.
    INFO Logs are saved here:
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_0_Marian_Devecka_bot.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_0_Marian_Devecka_game.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_1_CherryPi_bot.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_1_CherryPi_game.log
    INFO ---
    INFO Replays are saved here:
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_0.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_0.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_1.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_1.rep
    INFO ---
    INFO Frame information is saved here:
    INFO ---
    INFO Game results are saved here:
    INFO ---
    WARNING Not all result files have been recorded for game 'GAME_C5022697'
    WARNING Expected 2 result files, got 0
    WARNING Assuming a crash happened.
    ERROR Game has crashed!

### Steps to reproduce
Just run `scbw.play --bots "Marian Devecka" "CherryPi" --show_all --game_speed 10 --log_level=DEBUG`. Actual bots does not matter, Game speed also.

The games played normally, games finished, results in the VNC shown, but application reports crash.

This is both on Docker Machine and just Docker for Windows

Please run the command issued with  `--log_level=DEBUG` parameter and log:

    INFO Game GAME_C5022697 finished in 326.08 seconds.
    INFO Logs are saved here:
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_0_Marian_Devecka_bot.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_0_Marian_Devecka_game.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_1_CherryPi_bot.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_1_CherryPi_game.log
    INFO ---
    INFO Replays are saved here:
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_0.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_0.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_1.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_1.rep
    INFO ---
    INFO Frame information is saved here:
    INFO ---
    INFO Game results are saved here:
    INFO ---
    WARNING Not all result files have been recorded for game 'GAME_C5022697'
    WARNING Expected 2 result files, got 0
    WARNING Assuming a crash happened.
    ERROR Game has crashed!
    DEBUG running containers: ['f2b3f1e296a5', 'a883a0456d86']
    DEBUG running containers: ['f2b3f1e296a5', 'a883a0456d86']
    DEBUG running containers: ['f2b3f1e296a5', 'a883a0456d86']
    DEBUG running containers: ['f2b3f1e296a5', 'a883a0456d86']
    DEBUG running containers: ['f2b3f1e296a5', 'a883a0456d86']
    DEBUG running containers: []
    DEBUG Removing game containers
    f2b3f1e296a5
    a883a0456d86
    INFO Game GAME_C5022697 finished in 326.08 seconds.
    INFO Logs are saved here:
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_0_Marian_Devecka_bot.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_0_Marian_Devecka_game.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_1_CherryPi_bot.log
    INFO C:\Users\user\AppData\Roaming/scbw/logs\GAME_C5022697_1_CherryPi_game.log
    INFO ---
    INFO Replays are saved here:
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_0.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_0.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_1.rep
    INFO C:\Users\user\AppData\Roaming/scbw/maps/replays\GAME_C5022697_1.rep
    INFO ---
    INFO Frame information is saved here:
    INFO ---
    INFO Game results are saved here:
    INFO ---
    WARNING Not all result files have been recorded for game 'GAME_C5022697'
    WARNING Expected 2 result files, got 0
    WARNING Assuming a crash happened.
    ERROR Game has crashed!

### operating system

    both Windows 10 Home or Window 10 Pro

### docker version

output of command `docker version`:

    Client:
     Version:       18.01.0-ce
     API version:   1.35
     Go version:    go1.9.2
     Git commit:    03596f51b1
     Built: Thu Jan 11 22:29:41 2018
     OS/Arch:       windows/amd64
     Experimental:  false
     Orchestrator:  swarm

    Server:
     Engine:
      Version:      18.01.0-ce
      API version:  1.35 (minimum version 1.12)
      Go version:   go1.9.2
      Git commit:   03596f5
      Built:        Wed Jan 10 20:13:12 2018
      OS/Arch:      linux/amd64
      Experimental: false

or 

     Client:
      Version:       17.12.0-ce
      API version:   1.35
      Go version:    go1.9.2
      Git commit:    c97c6d6
      Built: Wed Dec 27 20:05:22 2017
      OS/Arch:       windows/amd64

     Server:
      Engine:
       Version:      17.12.0-ce
       API version:  1.35 (minimum version 1.12)
       Go version:   go1.9.2
       Git commit:   c97c6d6
       Built:        Wed Dec 27 20:12:29 2017
       OS/Arch:      linux/amd64
       Experimental: true

### scbw version

output of command `scbw.play -v`

    0.2b3 (+ waiting PR, but I saw that behavior earlier)

**Comment by michalsustr** [comment]
Did you have any `results.json` / `frames.csv` files in log dir?

I can't reproduce on linux.

Also... did you run `scbw.play --install` ? :)

**Comment by kant2002** [comment]
Thanks. `scbw.play --install` helped.
