### ISSUE TITLE
Error after downgrading scbw

### ISSUE THREAD

**Issue by MicroDK** [Games-and-Simulations/sc-docker#32]
### expected behaviour

After downgrading from eg. 0.2b3 to 0.2b2 I get this error when starting games:
`Some containers exited prematurely, please check logs`

### actual behaviour

Games should be able to run after downgrade if users for any reason needs to eg. due to BWAPI version support.

It seems scbw always pull the newest docker image. I can resolve the issue by changing the file `default.py` on line 23:

`SC_PARENT_IMAGE = 'ggaic/starcraft:java'`
to
`SC_PARENT_IMAGE = 'ggaic/starcraft:java-0.2b2'`

and then do `scbw.play --install`

### steps to reproduce

Update to newest version eg. 0.2b3:
`pip3.6 install scbw==0.2b3`
`scbw.play --install`

Downgrade to eg. 0.2b2:
`pip3.6 install scbw==0.2b2`
`scbw.play --install`

Start game:
`scbw.play --bots "CherryPi" "Marian Devecka" --show_all --log_level=DEBUG`

2.00MB [00:00, 14.6MB/s]                                                                            
1.00MB [00:00, 5.79MB/s]                                                                            
INFO Successfully downloaded CherryPi from SSCAIT server
1.00MB [00:00, 9.04MB/s]                                                                            
1.00MB [00:00, 8.71MB/s]                                                                            
INFO Successfully downloaded Marian Devecka from SSCAIT server
INFO launched BotPlayer:CherryPi:Z in container GAME_BDA49629_0_CherryPi
INFO launched BotPlayer:Marian Devecka:Z in container GAME_BDA49629_1_Marian Devecka
INFO Checking if game has launched properly...
ERROR Some containers exited prematurely, please check logs
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scbw/cli.py", line 178, in main
    game_result = run_game(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scbw/game.py", line 107, in run_game
    wait_callback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scbw/docker.py", line 302, in launch_game
    'Some containers exited prematurely, please check logs')
scbw.error.DockerException: Some containers exited prematurely, please check logs

### operating system

macOS 10.12.6

### docker version

Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

### scbw version

    0.2b3 and 0.2b2

**Comment by michalsustr** [comment]
Ok will update.

BTW BWAPI_375 support might be added, as well as resolving that slowness issue.

**Comment by MicroDK** [comment]
Sound nice! :D

**Comment by michalsustr** [comment]
> Now that I have used scbw a couple of days I can not live without it. :)

Good to hear :) I think the next level of my linux-fu mastery would be somehow attaching the debugger from the IDE :)

**Comment by michalsustr** [comment]
Fixed in `0.2b4`
