### ISSUE TITLE
Chat Broken

### ISSUE THREAD

**Issue by brownzach125** [Games-and-Simulations/sc-docker#33]
### expected behaviour
Pressing enter after typing text into the chat window during a game 
causes the entered text to appear on the screen.

### actual behaviour
The chat does not appear.

### steps to reproduce
Run a headful game with --show_all and attempt to enter text as the bot.
Chat works as expected for the human player.

scbw.play --bots zach_bot --docker_image=starcraft:game --log_level=DEBUG --human --show_all
DEBUG checking bot in /home/solevi/.scbw/bots/zach_bot
DEBUG found bot in /home/solevi/.scbw/bots/zach_bot
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_985C5E9F_0_human', '--volume', '/home/solevi/.scbw/logs:/app/logs:rw', '--volume', '/home/solevi/.scbw/bots:/app/bots:ro', '--volume', '/home/solevi/.scbw/maps:/app/sc/maps:rw', '--volume', '/home/solevi/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '/home/solevi/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '-p', '5900:5900', '-e', 'PLAYER_NAME=human', '-e', 'PLAYER_RACE=R', '-e', 'NTH_PLAYER=0', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_985C5E9F', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'TM_LOG_RESULTS=../logs/GAME_985C5E9F_0_results.json', '-e', 'TM_LOG_FRAMETIMES=../logs/GAME_985C5E9F_0_frames.csv', 'starcraft:game', '/app/play_human.sh', '--headful']
INFO launched HumanPlayer:human:R in container GAME_985C5E9F_0_human
DEBUG ['docker', 'run', '-d', '--rm', '--privileged', '--name', 'GAME_985C5E9F_1_zach_bot', '--volume', '/home/solevi/.scbw/logs:/app/logs:rw', '--volume', '/home/solevi/.scbw/bots:/app/bots:ro', '--volume', '/home/solevi/.scbw/maps:/app/sc/maps:rw', '--volume', '/home/solevi/.scbw/bwapi-data/BWTA:/app/sc/bwapi-data/BWTA:rw', '--volume', '/home/solevi/.scbw/bwapi-data/BWTA2:/app/sc/bwapi-data/BWTA2:rw', '--net', 'sc_net', '-p', '5901:5900', '--volume', '/home/solevi/.scbw/bots/zach_bot/write/GAME_985C5E9F_1:/app/sc/bwapi-data/write:rw', '-e', 'PLAYER_NAME=zach_bot', '-e', 'PLAYER_RACE=Z', '-e', 'NTH_PLAYER=1', '-e', 'NUM_PLAYERS=2', '-e', 'GAME_NAME=GAME_985C5E9F', '-e', 'MAP_NAME=/app/sc/maps/sscai/(2)Benzene.scx', '-e', 'GAME_TYPE=FREE_FOR_ALL', '-e', 'SPEED_OVERRIDE=0', '-e', 'BOT_NAME=zach_bot', '-e', 'BOT_FILE=zach_bot.jython', '-e', 'BOT_BWAPI=4.1.2', '-e', 'TM_LOG_RESULTS=../logs/GAME_985C5E9F_1_results.json', '-e', 'TM_LOG_FRAMETIMES=../logs/GAME_985C5E9F_1_frames.csv', 'starcraft:game', '/app/play_bot.sh', '--headful']
INFO launched BotPlayer:zach_bot:Z in container GAME_985C5E9F_1_zach_bot
INFO Checking if game has launched properly...
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
INFO Launching vnc viewer for HumanPlayer:human:R on port 5900
INFO Launching vnc viewer for BotPlayer:zach_bot:Z on port 5901
INFO 
In headful mode, you must specify and start the game manually.
Select the map, wait for bots to join the game and then start the game.
INFO Waiting until game is finished...
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
^CWARNING Caught interrupt, shutting down containers
WARNING This can take a moment, please wait.
DEBUG running containers: ['e3299e4ee47a', '8a6bf953e7e0']
e3299e4ee47a
8a6bf953e7e0
INFO Game cancelled

### operating system
    linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu `lsb_release -a`:

    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04
    Release:        16.04
    Codename:       xenial

### docker version

output of command `docker version`:

Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

### scbw version

output of command `scbw.play -v`

    0.2b3

**Comment by MicroDK** [comment]
If it is the bot games you try to input chat message into, does the bot not need to set a BWAPI variable to allow text input?

**Comment by michalsustr** [comment]
I think this a feature, not a bug :) I believe this is related to underlying BWAPI on what it (dis)allows - as the bot is playing no input is allowed I think.

**Comment by MicroDK** [comment]
I think there is a BWAPI variable that you can set in the bot, that allow/disallow chat input when the bot is playing.

**Comment by brownzach125** [comment]
My bad. You are correct. game.enableFlag(1)
