### ISSUE TITLE
Downloads from SSCAIT not working on Windows

### ISSUE THREAD

**Issue by Jabbo16** [Games-and-Simulations/sc-docker#4]
Got it fixed on Windows 10 by adding this lines just before the the download methods at [/scbw/bot_storage.py](../blob/dev/scbw/bot_storage.py)

```
opener = urllib.request.build_opener()
opener.addheaders=[('User-Agent','Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1941.0 Safari/537.36')]
urllib.request.install_opener(opener)
```

Main problem I found and also why I didnt create a pull request for this is that after this change the following method threw an exception and I couldnt fix it.
> os.remove(f'{base_dir}/AI.zip')

The exception its thrown because its trying to delete the file but is already in use by the system.
Adding a sleep didnt work.

**Comment by michalsustr** [comment]
Updated. I think the exception was thrown because `os.remove` was previously done within `with` block, which works on Linux, but not on Windows (because of different file table handling)
