### ISSUE TITLE
Replay info messages are shown twice in Windows

### ISSUE THREAD

**Issue by MicroDK** [Games-and-Simulations/sc-docker#41]
### expected behaviour

On Windows, the messages about where to find replays are shown twice for each bot.

### actual behaviour

The messages about where to find replays should only be shown once for each bot.

### steps to reproduce

scbw.play --bots "Microwave" "ZZZKBot" --headless --read_overwrite --game_speed 0 --map "sscai/(4)Empire of the Sun.scm"
Error: No machine name(s) specified and no "default" machine exists
INFO launched BotPlayer:Microwave:Z
INFO launched BotPlayer:ZZZKBot:Z
INFO Waiting until game GAME_4C8026FC is finished...
INFO Overwriting bot files
INFO Game GAME_4C8026FC finished in 41.55512762069702 seconds.
INFO ---
INFO Logs are saved here:
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_0_Microwave_bot.log
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_0_Microwave_game.log
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_1_ZZZKBot_bot.log
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_1_ZZZKBot_game.log
INFO ---
INFO Replays are saved here:
INFO C:\Users\micky\AppData\Roaming/scbw/maps/replays\GAME_4C8026FC_0.rep
INFO C:\Users\micky\AppData\Roaming/scbw/maps/replays\GAME_4C8026FC_0.rep
INFO C:\Users\micky\AppData\Roaming/scbw/maps/replays\GAME_4C8026FC_1.rep
INFO C:\Users\micky\AppData\Roaming/scbw/maps/replays\GAME_4C8026FC_1.rep
INFO ---
INFO Frame information is saved here:
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_0_frames.csv
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_1_frames.csv
INFO ---
INFO Game results are saved here:
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_0_results.json
INFO C:\Users\micky\AppData\Roaming/scbw/logs\GAME_4C8026FC_1_results.json
INFO ---
INFO Winner is BotPlayer:Microwave:Z (player 0)

### operating system

Windows 10

### docker version

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

### scbw version

    0.2b7

**Comment by michalsustr** [comment]
Oh yeah, right, I forgot about that one. :) it looks up *.rep and *.REP files, which are matched twice on windows, not once on linux :)
