### ISSUE TITLE
Automatic install on PyPi package download

### ISSUE THREAD

**Issue by michalsustr** [Games-and-Simulations/sc-docker#45]
Currently we need to run `scbw.play --install`, can it be run on package install?

**Comment by kant2002** [comment]
I think would be reasonable to implement following approach:

Let's have 
1. full verification 
2. and quick verification of required dependencies.

Full verification right now is the same as `scbw.play --install`, and quick verification relying on file presence. For example we will add writing file 'install.touch' with magic string sitting in the file. We will have 3 scenarios

Let's name current process 

**Case 1: 'install.marker' file is missing. Parameter `--install` is not passed.**
1. Run `scbw.install()`
2. Create 'install.marker' with version specific content in the `~/scbw/` folder

**Case 2: 'install.marker' file is present, but content is unexpected. Parameter `--install` is not passed.**
1. Run `scbw.install()`
2. Overwirte 'install.marker' with version specific content in the `~/scbw/` folder

**Case 3: Parameter `--install` is passed.**
1. Run `scbw.install()`
2. Create 'install.marker' with version specific content in the `~/scbw/` folder

/cc: @michalsustr

**Comment by michalsustr** [comment]
Case 1 & 2 are implemented via docker versioning scheme - if we have the image of the right version, it can be assumed we have installed things correctly.

Case 3 still stays there.

https://github.com/Games-and-Simulations/sc-docker/blob/master/scbw/cli.py#L157
