### ISSUE TITLE
Linux Feedback

### ISSUE THREAD

**Issue by chrishare** [Games-and-Simulations/sc-docker#6]
Hey guys,

Thanks for the project - it's really interesting. I got it to work for me, here were some minor issues I hit:
1/ Hitting http instead of https for maps/bots - doesn't seem to be required (http gives a 301 redirect)
2/ Getting http 403 for maps and bots - I think python is sending some python User-Agent that Cloudflare doesn't like. Something like this will fix it:
        opener = urllib.request.build_opener()
        opener.addheaders = [('User-agent', 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0')]
        urllib.request.install_opener(opener)
3/ I ended up having to restart my entire machine to add my personal user to the docker group, for some reason (nothing to do with this project).
4/ The docker version check might be a bit tight - i.e. I'm on Docker version 17.12.0-ce, build c97c6d6 (newer but doesn't pass the check).

**Comment by michalsustr** [comment]
Thanks for feedback! :)

1) there's some bug on our local network, that's why I had to use http
2) added
3) Hmm... it should be enough to logout/login.
4) Removed, it was pretty much unnecessary, sometimes I'm too strict :)
