### ISSUE TITLE
No bot crash logs in scbw/logs

### ISSUE THREAD

**Issue by MicroDK** [Games-and-Simulations/sc-docker#64]
### expected behaviour
If a bot crashes crash logs should be available in C:\Users\micky\AppData\Roaming\scbw\logs.

### actual behaviour
If a bot crashes crash logs are normally stored in StarCraft\Errors, but these files are not copied to C:\Users\micky\AppData\Roaming\scbw\logs.

### operating system

    Windows 10 Pro

### docker version

output of command `docker version`:

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

### scbw version

output of command `scbw.play -v`

    0.2b7

**Comment by kant2002** [comment]
This looks like duplicate to #48. Looks like only adding additional volume is needed for this change. If map `<SC>/Errors` folder to additional folder inside game specific folder, that could be done relatively easy.
