### ISSUE TITLE
Feature Request - Allow Repeat Flag 

### ISSUE THREAD

**Issue by RothNath** [Games-and-Simulations/sc-docker#73]
For running large amounts of games it would be helpful to have a repeat flag. 

For example: --repeat 100 or --r 50 etc. 

Currently using bash scripts to automate on Windows, for example:

While($true)
	{
	$i++
	scbw.play --bots "Iron" "Steamhammer" --auto_launch --game_speed 0 
	Write-Host "Action has run $i times" 
	}.

 I think it would be a helpful feature.

**Comment by MicroDK** [comment]
A shorter script: :D
```
for /L %i in (1,1,40) do scbw.play --bots "Microwave" "Andrew Smith" --headless --read_overwrite --game_speed 0 --map "sscai/(4)Empire of the Sun.scm"
```
