### ISSUE TITLE
pip can not update to scbw 1.0.2

### ISSUE THREAD

**Issue by MicroDK** [Games-and-Simulations/sc-docker#76]
### expected behaviour

When trying to update scbw to 1.0.2, which should be the latest release, I should be able to upgrade with no problems.

### actual behaviour

I get this errors:
No matching distribution found for scbw==1.0.2

### steps to reproduce

pip3.6 install scbw==1.0.2
Collecting scbw==1.0.2
  Could not find a version that satisfies the requirement scbw==1.0.2 (from versions: 1.0.2f, 0.2a0, 0.2a1, 0.2a2, 0.2a3, 0.2a4, 0.2a5, 0.2a6, 0.2a7, 0.2a8, 0.2a9, 0.2a10, 0.2a11, 0.2a12, 0.2a13, 0.2a14, 0.2a15, 0.2a16, 0.2a17, 0.2a19, 0.2a20, 0.2a21, 0.2b1, 0.2b2, 0.2b3, 0.2b4, 0.2b5, 0.2b6, 0.2b7, 0.2b8, 0.2b9, 0.2b10, 1.0, 1.0.1)
No matching distribution found for scbw==1.0.2

### operating system

    macOS 10.12.6

### docker version

output of command `docker version`:

Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

### scbw version

output of command `scbw.play -v`

    1.0.1

**Comment by Jabbo16** [comment]
Try with `scbw==1.0.2f`

**Comment by MicroDK** [comment]
Thanks but I managed to update with `pip3.6 install -U scbw`.

**Comment by MicroDK** [comment]
But I had to uninstall first: `pip3.6 uninstall scbw==1.0.1`
And then install: `pip3.6 install scbw==1.0.2f`
